import Head from 'next/head';
import { useRouter } from "next/router";
import styles from "../../styles/Users.module.css";


interface UserProps {
  dataUsers : Array<any>;
}

export default function Users(props : UserProps) {
  const {dataUsers} = props;
  const router = useRouter();
  return (

    <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
    {/* <Navbar/> */}
    {/* <Navbar/> */}
    <div>
        {dataUsers.map((user) => (
        <div key={user.id} className={styles.card} onClick={() => router.push(`/users/${user.id}`)}>
        <p>{user.name}</p>
        <p>{user.email}</p>
        </div>
        ))}
    </div>
    {/* <Footer/> */}

    </main>
  </div>

  )
}


export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const dataUsers = await res.json();
  return {
    props : {
      dataUsers,
    }
  }
}
