import Head from 'next/head';
import { useRouter } from "next/router";
import styles from "../../styles/Blog.module.css";

interface Post {
    id : number;
    title : string;
    body : string;
  }
  
  interface BlogProps {
    dataBlog : Post[]
  }
  

  export default function Blog(props : BlogProps) {
    const {dataBlog} = props;
    return (
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>

        <div>

        {dataBlog.map((news) =>(
         <div key={news.id} className={styles.card}>
            <h3><strong>{news.title}</strong></h3>
            <p>{news.body}</p>
         </div>   
        ))}

        </div>
        
        </main>
        </div>
    );
  }

export async function getServerSideProps() {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts");
    const dataBlog = await res.json();
    
    return {
      props : {
        dataBlog,
      }
    }
  }
